import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase-shim';
import { useCompany } from './useCompany';

export interface TablePayment {
  id: string;
  company_id: string;
  session_id: string;
  table_id: string;
  command_id: string | null;
  amount_cents: number;
  payer_name: string | null;
  payment_method: string;
  payment_type: 'partial' | 'advance' | 'full';
  notes: string | null;
  nsu: string | null;
  created_at: string;
}

export function useTablePayments(sessionId?: string) {
  const { data: company } = useCompany();
  const queryClient = useQueryClient();

  const { data: payments = [], isLoading, error } = useQuery({
    queryKey: ['table-payments', sessionId],
    queryFn: async () => {
      if (!sessionId) return [];
      
      const { data, error } = await supabase
        .from('table_payments')
        .select('*')
        .eq('session_id', sessionId)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data as TablePayment[];
    },
    enabled: !!sessionId,
  });

  const addPayment = useMutation({
    mutationFn: async ({ 
      sessionId, 
      tableId,
      commandId,
      amountCents,
      payerName,
      paymentMethod,
      paymentType,
      notes,
      externalNsu
    }: { 
      sessionId: string;
      tableId: string;
      commandId?: string;
      amountCents: number;
      payerName?: string;
      paymentMethod: string;
      paymentType: 'partial' | 'advance' | 'full';
      notes?: string;
      externalNsu?: string; // NSU from external provider (TEF, POS, etc.)
    }) => {
      if (!company?.id) throw new Error('No company');
      
      const { data, error } = await supabase
        .from('table_payments')
        .insert([{ 
          company_id: company.id,
          session_id: sessionId,
          table_id: tableId,
          command_id: commandId || null,
          amount_cents: amountCents,
          payer_name: payerName || null,
          payment_method: paymentMethod,
          payment_type: paymentType,
          notes: notes || null,
          nsu: externalNsu || null, // NSU will be auto-generated by trigger if not provided
        }])
        .select()
        .single();

      if (error) throw error;
      return data as TablePayment;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['table-payments'] });
      queryClient.invalidateQueries({ queryKey: ['table-sessions'] });
    },
  });

  const totalPaidCents = payments.reduce((sum, p) => sum + p.amount_cents, 0);

  return {
    payments,
    totalPaidCents,
    isLoading,
    error,
    addPayment,
  };
}
