import { useState } from 'react';
import { KDSOrder, ItemStatus } from '@/hooks/useKDS';
import { OrderStatus, Order } from '@/hooks/useOrders';
import { useItemStatus } from '@/hooks/useItemStatus';
import { useCompany } from '@/hooks/useCompany';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import {
  Clock,
  AlertTriangle,
  ChefHat,
  CheckCircle2,
  ArrowRight,
  User,
  Package,
  Edit,
  Timer,
  Play,
  ListChecks,
  Expand,
  Truck,
  Globe,
  PhoneCall,
  Store,
  UtensilsCrossed,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { OrderReprintButtons } from '@/components/orders/OrderReprintButtons';
import {
  OrderStageTimers,
  getAlertLevel,
  getCurrentStageTime,
  OrderTimestamps,
} from './OrderStageTimers';
import { PartialPreparationDialog } from './PartialPreparationDialog';
import { DispatchDialog } from './DispatchDialog';
import { printPartialKitchenTicket } from '@/lib/print/partialKitchenTicket';
import { toast } from 'sonner';
import { buildItemChildLines } from '@/lib/receiptFormatting';
import { OrderExpandDialog } from '@/components/orders/OrderExpandDialog';
import { getOrderTypeLabel } from '@/lib/orderTypeLabel';
import { parsePizzaSnapshot } from '@/lib/parsePizzaSnapshot';

// Ícones para tipos de pedido
const orderTypeIcons = {
  globe: Globe,
  phone: PhoneCall,
  store: Store,
  package: Package,
  utensils: UtensilsCrossed,
};

// Helper to detect auto-generated notes that should not be displayed as observations
const looksLikeAutoGenerated = (notes: string): boolean => {
  const n = notes.toLowerCase();
  return (
    (n.includes(':') && (n.includes(',') || n.includes('|'))) ||
    /\d+\/\d+/.test(notes) ||
    n.includes('sabor') ||
    n.includes('borda') ||
    n.includes('bebida')
  );
};

interface KDSOrderCardProps {
  order: KDSOrder & Partial<OrderTimestamps>;
  onStatusChange: (orderId: string, status: OrderStatus, orderNumber?: number, customerName?: string | null, delivererId?: string | null) => void;
  isUpdating?: boolean;
  warnAfterMinutes?: number;
  dangerAfterMinutes?: number;
}

const statusConfig: Record<OrderStatus, { label: string; color: string; next: OrderStatus | null }> = {
  novo: { label: 'Novo', color: 'bg-yellow-500', next: 'preparo' },
  preparo: { label: 'Preparo', color: 'bg-orange-500', next: 'pronto' },
  pronto: { label: 'Pronto', color: 'bg-green-500', next: 'em_rota' },
  em_rota: { label: 'Em Rota', color: 'bg-blue-500', next: 'entregue' },
  entregue: { label: 'Entregue', color: 'bg-slate-500', next: null },
};

const itemStatusConfig: Record<ItemStatus, { label: string; color: string; bgColor: string }> = {
  pendente: { label: 'Pendente', color: 'text-slate-400', bgColor: 'bg-slate-700/50' },
  preparo: { label: 'Preparo', color: 'text-orange-400', bgColor: 'bg-orange-900/30' },
  pronto: { label: 'Pronto', color: 'text-green-400', bgColor: 'bg-green-900/30' },
  cancelado: { label: 'Cancelado', color: 'text-red-400', bgColor: 'bg-red-900/30' },
};

export function KDSOrderCard({
  order,
  onStatusChange,
  isUpdating,
  warnAfterMinutes = 10,
  dangerAfterMinutes = 20,
}: KDSOrderCardProps) {
  const [partialDialogOpen, setPartialDialogOpen] = useState(false);
  const [expandOpen, setExpandOpen] = useState(false);
  const [dispatchDialogOpen, setDispatchDialogOpen] = useState(false);
  const { data: company } = useCompany();
  const { updateItemStatus, updateMultipleItemsStatus, startAllItemsPreparation } = useItemStatus();

  const config = statusConfig[order.status];
  const createdAt = new Date(order.created_at);

  // Calculate item statistics
  const activeItems = order.items.filter(i => i.edit_status !== 'removed');
  const itemStats = {
    total: activeItems.length,
    pendente: activeItems.filter(i => !i.item_status || i.item_status === 'pendente').length,
    preparo: activeItems.filter(i => i.item_status === 'preparo').length,
    pronto: activeItems.filter(i => i.item_status === 'pronto').length,
  };
  const isPartialPreparation = itemStats.preparo > 0 || (itemStats.pronto > 0 && itemStats.pronto < itemStats.total);

  // Calculate alert level based on current stage time
  const currentStageTime = getCurrentStageTime({
    created_at: order.created_at,
    accepted_at: (order as any).accepted_at,
    ready_at: (order as any).ready_at,
    dispatched_at: (order as any).dispatched_at,
    delivered_at: (order as any).delivered_at,
    status: order.status,
  });

  const alertLevel = getAlertLevel(currentStageTime, warnAfterMinutes, dangerAfterMinutes);

  // Check if order is delivery type
  const isDeliveryOrder = order.order_type === 'delivery';

  // Handle full order status change
  const handleAdvanceStatus = async (delivererId?: string) => {
    if (config.next) {
      // If going from novo to preparo, also update all items
      if (order.status === 'novo' && config.next === 'preparo') {
        await startAllItemsPreparation.mutateAsync(order.id);
      }
      // Pass orderNumber, customerName, and delivererId for dispatch
      onStatusChange(
        order.id, 
        config.next, 
        (order as any).order_number,
        order.customer_name,
        delivererId || null
      );
    }
  };

  // Handle dispatch button click - requires deliverer selection for delivery orders
  const handleDispatchClick = () => {
    if (isDeliveryOrder) {
      // Open dispatch dialog to select deliverer
      setDispatchDialogOpen(true);
    } else {
      // Non-delivery orders can be dispatched directly
      handleAdvanceStatus();
    }
  };

  // Handle dispatch confirmation with deliverer
  const handleDispatchConfirm = (delivererId: string) => {
    handleAdvanceStatus(delivererId);
    setDispatchDialogOpen(false);
  };

  // Handle single item status change
  const handleItemStatusChange = async (itemId: string, newStatus: ItemStatus) => {
    try {
      await updateItemStatus.mutateAsync({ 
        itemId, 
        status: newStatus,
        orderId: order.id 
      });
      toast.success(`Item ${newStatus === 'preparo' ? 'em preparo' : 'pronto'}`);
    } catch (error) {
      console.error('Error updating item:', error);
      toast.error('Erro ao atualizar item');
    }
  };

  // Handle partial preparation confirmation
  const handlePartialConfirm = async (selectedItemIds: string[], printSelected: boolean) => {
    try {
      await updateMultipleItemsStatus.mutateAsync({ 
        itemIds: selectedItemIds, 
        status: 'preparo',
        orderId: order.id
      });
      
      if (printSelected) {
        const selectedItems = order.items.filter(i => selectedItemIds.includes(i.id));
        printPartialKitchenTicket(order as any, selectedItems, company?.name);
      }
      
      setPartialDialogOpen(false);
    } catch (error) {
      console.error('Error starting partial prep:', error);
      toast.error('Erro ao iniciar preparo parcial');
    }
  };

  const getNextAction = () => {
    switch (order.status) {
      case 'novo': return 'Iniciar Preparo (Tudo)';
      case 'preparo': return 'Marcar Pronto';
      case 'pronto': return 'Despachar';
      default: return null;
    }
  };

  // Check if order has edits
  const hasEdits = order.is_edited || order.items.some(item => item.edit_status);

  // Status-based card background colors (high contrast versions)
  const getStatusBackground = () => {
    switch (order.status) {
      case 'novo': return 'bg-blue-800 text-white font-semibold';
      case 'preparo': return 'bg-orange-600 text-white font-semibold';
      case 'pronto': return 'bg-green-700 text-white font-semibold';
      case 'em_rota': return 'bg-purple-800 text-white font-semibold';
      case 'entregue': return 'bg-gray-700 text-white font-semibold';
      default: return 'bg-slate-900';
    }
  };

  return (
    <>
      <Card 
        className={cn(
          "border-2 transition-all w-full max-w-full overflow-hidden",
          getStatusBackground(),
          // Alert-based ring without animation on card (no animate-pulse on the card itself)
          alertLevel.level === 'danger' && "ring-4 ring-red-500",
          alertLevel.level === 'warn' && !order.is_overdue && "ring-2 ring-yellow-300",
          alertLevel.level === 'ok' && order.is_overdue && "ring-4 ring-red-500",
          hasEdits && "ring-2 ring-amber-400"
        )}
      >
        <CardHeader className="py-2 sm:py-3 px-3 sm:px-4 border-b border-white/20">
          {/* TIPO DO PEDIDO - Badge destacado no topo do KDS */}
          {(() => {
            const typeInfo = getOrderTypeLabel(order.order_type, (order as any).source, (order as any).eat_here);
            const TypeIcon = orderTypeIcons[typeInfo.icon];
            const isTableOrder = order.order_type === 'table';
            const isComandaOrder = order.order_type === 'dine_in';
            const isQROrder = order.order_type === 'qrcode' || (order as any).source === 'qrcode';
            const tableNumber = (order as any).table_number || order.customer_name?.match(/MESA (\d+)/)?.[1];
            const comandaNumber = order.customer_name?.match(/COMANDA (\d+)/)?.[1] || (order as any).comanda_number;
            
            // Check if QR order has table or comanda in notes
            const notesMatch = (order as any).notes?.match(/Mesa:\s*(\d+)|Comanda:\s*(\d+)/i);
            const qrTableFromNotes = notesMatch?.[1];
            const qrComandaFromNotes = notesMatch?.[2];
            
            return (
              <div 
                className={cn(
                  "flex items-center justify-center gap-1 sm:gap-2 py-1.5 sm:py-2 px-2 sm:px-4 rounded-md mb-2 sm:mb-3 font-black text-sm sm:text-lg tracking-wide truncate",
                  isQROrder ? "bg-purple-600" : typeInfo.color,
                  isQROrder ? "text-white" : (typeInfo.textColor === '#000' ? 'text-black' : 'text-white'),
                  // Piscar apenas a tag quando tem alerta de atraso
                  (alertLevel.level === 'danger' || (alertLevel.level === 'ok' && order.is_overdue)) && "animate-pulse",
                  alertLevel.level === 'warn' && !order.is_overdue && "animate-[pulse_2s_ease-in-out_infinite]"
                )}
              >
                <TypeIcon className="h-4 w-4 sm:h-6 sm:w-6 flex-shrink-0" />
                <span className="truncate">
                  {isQROrder && (tableNumber || qrTableFromNotes) ? (
                    `📱 QR MESA ${tableNumber || qrTableFromNotes} 📱`
                  ) : isQROrder && (comandaNumber || qrComandaFromNotes) ? (
                    `📱 QR COMANDA ${comandaNumber || qrComandaFromNotes} 📱`
                  ) : isTableOrder && tableNumber ? (
                    `★★★ MESA ${tableNumber} ★★★`
                  ) : isComandaOrder && comandaNumber ? (
                    `★★★ COMANDA ${comandaNumber} ★★★`
                  ) : (
                    typeInfo.label
                  )}
                </span>
              </div>
            );
          })()}

          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className={cn("w-3 h-3 rounded-full", config.color)} />
              {/* For table/comanda orders, show command info instead of order number */}
              {order.order_type === 'table' ? (
                <span className="font-bold text-lg text-white">
                  {order.customer_name || `Mesa ${(order as any).table_number || '?'}`}
                </span>
              ) : order.order_type === 'dine_in' ? (
                <span className="font-bold text-lg text-white">
                  {order.customer_name || 'Comanda'}
                </span>
              ) : (
                <span className="font-bold text-lg text-white">
                  #{(order as any).order_number ? String((order as any).order_number).padStart(3, '0') : order.id.slice(-4).toUpperCase()}
                </span>
              )}
            </div>
            
            <div className="flex items-center gap-2">
              {/* Alert badges */}
              {alertLevel.level === 'danger' && (
                <Badge className="bg-red-500 text-white font-bold animate-pulse">
                  <AlertTriangle className="w-3 h-3 mr-1" />
                  CRÍTICO
                </Badge>
              )}
              {alertLevel.level === 'warn' && (
                <Badge className="bg-yellow-500 text-black font-bold">
                  <Timer className="w-3 h-3 mr-1" />
                  ALERTA
                </Badge>
              )}
              {hasEdits && (
                <Badge className="bg-amber-500 text-black font-bold animate-pulse">
                  <Edit className="w-3 h-3 mr-1" />
                  EDITADO
                </Badge>
              )}
              {isPartialPreparation && (
                <Badge className="bg-purple-500 text-white font-bold">
                  <ListChecks className="w-3 h-3 mr-1" />
                  PARCIAL
                </Badge>
              )}
            </div>
          </div>

          {/* Item Progress Bar */}
          {order.status !== 'novo' && (
            <div className="mt-2 flex items-center gap-2 text-xs">
              <span className="text-white/70">Progresso:</span>
              <div className="flex-1 h-2 bg-white/20 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-gradient-to-r from-orange-400 to-green-400 transition-all"
                  style={{ width: `${((itemStats.preparo + itemStats.pronto) / itemStats.total) * 100}%` }}
                />
              </div>
              <span className="text-white font-medium">
                {itemStats.pronto}/{itemStats.total}
              </span>
            </div>
          )}

          {/* Stage Timers */}
          <div className="mt-2">
            <OrderStageTimers
              order={{
                created_at: order.created_at,
                accepted_at: (order as any).accepted_at,
                ready_at: (order as any).ready_at,
                dispatched_at: (order as any).dispatched_at,
                delivered_at: (order as any).delivered_at,
                status: order.status,
              }}
              warnAfterMinutes={warnAfterMinutes}
              dangerAfterMinutes={dangerAfterMinutes}
              compact={true}
            />
          </div>

          {order.customer_name && (
            <div className="flex items-center gap-2 mt-2 text-sm text-white">
              <User className="w-3 h-3 text-white/70" />
              <span className="font-medium">{order.customer_name}</span>
            </div>
          )}
        </CardHeader>

        <CardContent className="py-2 sm:py-3 px-3 sm:px-4 max-h-[50vh] overflow-y-auto">
          {/* Items */}
          <div className="space-y-1.5 sm:space-y-2">
            {order.items.map((item) => {
              const isNew = item.edit_status === 'new';
              const isModified = item.edit_status === 'modified';
              const isRemoved = item.edit_status === 'removed';
              const itemStatus = item.item_status || 'pendente';
              const itemStatusInfo = itemStatusConfig[itemStatus];
              
              return (
                <div 
                  key={item.id} 
                  className={cn(
                    "flex items-start justify-between p-2 rounded",
                    isNew ? "bg-green-900/50 border border-green-500" :
                    isModified ? "bg-amber-900/50 border border-amber-500" :
                    isRemoved ? "bg-red-900/30 border border-red-500/50 opacity-70" :
                    itemStatusInfo.bgColor
                  )}
                >
                  <div className="flex-1">
                    <div className="flex items-center gap-2 flex-wrap">
                      {/* Item Status Badge */}
                      {!isRemoved && order.status !== 'novo' && (
                        <Badge className={cn("text-xs", itemStatusInfo.color, "bg-transparent border", 
                          itemStatus === 'preparo' && "border-orange-500",
                          itemStatus === 'pronto' && "border-green-500",
                          itemStatus === 'pendente' && "border-slate-500"
                        )}>
                          {itemStatusInfo.label}
                        </Badge>
                      )}
                      
                      {/* Edit Status Badge */}
                      {isNew && (
                        <Badge className="bg-green-500 text-black font-bold text-xs">
                          [NOVO]
                        </Badge>
                      )}
                      {isModified && (
                        <Badge className="bg-amber-500 text-black font-bold text-xs">
                          [ALTERADO]
                        </Badge>
                      )}
                      {isRemoved && (
                        <Badge className="bg-red-500 text-white font-bold text-xs">
                          [REMOVIDO]
                        </Badge>
                      )}
                      
                      {/* Quantity */}
                      <span className={cn(
                        "text-lg font-bold",
                        isNew ? "text-green-400" :
                        isModified ? "text-amber-400" :
                        isRemoved ? "text-red-400 line-through" :
                        "text-purple-400"
                      )}>
                        {item.quantity}x
                      </span>
                      
                      {/* Product Name - cleaned of embedded details */}
                      {(() => {
                        let cleanName = item.product_name || '';
                        // Remove "(Escolha o sabor...)" or "(Esolha..." suffix
                        const parenIdx = cleanName.indexOf(' (Escolha');
                        if (parenIdx > 0) cleanName = cleanName.substring(0, parenIdx);
                        const parenIdx2 = cleanName.indexOf(' (Esolha');
                        if (parenIdx2 > 0) cleanName = cleanName.substring(0, parenIdx2);
                        
                        return (
                          <span className={cn(
                            "font-medium",
                            isNew ? "text-green-100 font-bold" :
                            isModified ? "text-amber-100 font-bold" :
                            isRemoved ? "text-red-300 line-through" :
                            "text-white"
                          )}>
                            {cleanName}
                          </span>
                        );
                      })()}
                    </div>

                    {/* Pizza-specific structured details */}
                    {(() => {
                      const pizzaData = parsePizzaSnapshot((item as any).selected_options_json);
                      if (!pizzaData) return null;

                      return (
                        <div className="mt-1 space-y-0.5 pl-6">
                          {/* Tamanho */}
                          {pizzaData.size && (
                            <p className="text-xs text-cyan-300 font-medium">
                              📏 Tamanho: {pizzaData.size}
                            </p>
                          )}
                          {/* Massa */}
                          {pizzaData.doughType && (
                            <p className="text-xs text-amber-300 font-medium">
                              🫓 Massa: {pizzaData.doughType}
                            </p>
                          )}
                          {/* Sabores */}
                          {pizzaData.flavors.length > 0 && (
                            <div>
                              <p className="text-xs text-white/70 font-medium">🍕 Sabores:</p>
                              {pizzaData.flavors.map((f, idx) => (
                                <p key={idx} className="text-xs text-white/90 pl-3">
                                  {pizzaData.flavors.length > 1 ? `1/${pizzaData.flavors.length} ` : ''}{f.name}
                                  {f.removedIngredients.length > 0 && (
                                    <span className="text-red-300"> (sem {f.removedIngredients.join(', ')})</span>
                                  )}
                                  {f.observation && (
                                    <span className="text-amber-300 italic"> — {f.observation}</span>
                                  )}
                                </p>
                              ))}
                            </div>
                          )}
                          {/* Borda */}
                          <p className="text-xs text-purple-300 font-medium">
                            🔘 Borda: {pizzaData.borderName 
                              ? `${pizzaData.borderName}${pizzaData.borderType ? ` (${pizzaData.borderType})` : ''}`
                              : 'Sem borda'}
                          </p>
                          {/* Opcionais */}
                          {pizzaData.optionals.length > 0 && (
                            <div>
                              <p className="text-xs text-white/70 font-medium">➕ Opcionais:</p>
                              {pizzaData.optionals.map((o, idx) => (
                                <p key={idx} className="text-xs text-white/80 pl-3">
                                  {o.label}
                                </p>
                              ))}
                            </div>
                          )}
                        </div>
                      );
                    })()}

                    {/* Non-pizza child lines (regular options) */}
                    {(() => {
                      const pizzaData = parsePizzaSnapshot((item as any).selected_options_json);
                      if (pizzaData) return null; // Already shown via pizza rendering above

                      let childLines = buildItemChildLines({
                        selectedOptionsJson: (item as any).selected_options_json,
                        notes: item.notes,
                        childMaxLen: 40,
                      });

                      // Fallback: if product_name has embedded details, parse them
                      if (!childLines.length && item.product_name?.includes('|')) {
                        const afterParen = item.product_name.match(/\(([^)]+)\)/);
                        if (afterParen) {
                          childLines = buildItemChildLines({
                            selectedOptionsJson: null,
                            notes: afterParen[1],
                            childMaxLen: 40,
                          });
                        }
                      }

                      if (!childLines.length) return null;

                      return (
                        <div className="mt-1 space-y-0.5 pl-6">
                          {childLines.map((line, idx) => (
                            <p
                              key={idx}
                              className={cn(
                                "text-xs text-white/80",
                                isNew ? "text-green-200" :
                                isModified ? "text-amber-200" :
                                isRemoved ? "text-red-300 line-through" :
                                ""
                              )}
                            >
                              {line}
                            </p>
                          ))}
                        </div>
                      );
                    })()}

                    {/* Notes / Observations */}
                    {item.notes && (
                      <p className={cn(
                        "text-sm mt-1",
                        isNew ? "text-green-300" :
                        isModified ? "text-amber-300 font-bold" :
                        isRemoved ? "text-red-400 line-through" :
                        "text-amber-400"
                      )}>
                        📝 {item.notes}
                      </p>
                    )}
                    
                    {/* Show notes change for modified items */}
                    {isModified && item.previous_notes !== item.notes && (
                      <p className="text-xs text-amber-300 mt-1">
                        📝 Obs: "{item.previous_notes || '-'}" → "{item.notes || '-'}"
                      </p>
                    )}
                  </div>
                  
                  <div className="flex items-center gap-2 ml-2">
                    {/* Sector Badge */}
                    {item.sector_name && !isRemoved && (
                      <Badge 
                        variant="outline" 
                        className="flex-shrink-0"
                        style={{ borderColor: item.sector_color, color: item.sector_color }}
                      >
                        {item.sector_name}
                      </Badge>
                    )}
                    
                    {/* Item Quick Actions */}
                    {!isRemoved && order.status !== 'novo' && (
                      <div className="flex gap-1">
                        {itemStatus === 'pendente' && (
                          <Button
                            size="sm"
                            variant="ghost"
                            className="h-7 px-2 text-orange-400 hover:bg-orange-500/20"
                            onClick={() => handleItemStatusChange(item.id, 'preparo')}
                            disabled={updateItemStatus.isPending}
                          >
                            <Play className="w-3 h-3" />
                          </Button>
                        )}
                        {(itemStatus === 'pendente' || itemStatus === 'preparo') && (
                          <Button
                            size="sm"
                            variant="ghost"
                            className="h-7 px-2 text-green-400 hover:bg-green-500/20"
                            onClick={() => handleItemStatusChange(item.id, 'pronto')}
                            disabled={updateItemStatus.isPending}
                          >
                            <CheckCircle2 className="w-3 h-3" />
                          </Button>
                        )}
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          {/* Notes */}
          {order.notes && (
            <div className="mt-3 p-2 rounded bg-amber-500/10 border border-amber-500/30">
              <p className="text-sm text-amber-300">
                <strong>Obs:</strong> {order.notes}
              </p>
            </div>
          )}

          {/* Address Notes */}
          {(order as any).address_notes && (
            <div className="mt-2 p-2 rounded bg-purple-500/10 border border-purple-500/30">
              <p className="text-sm text-purple-300">
                <strong>📍 Endereço:</strong> {(order as any).address_notes}
              </p>
            </div>
          )}

          {/* Ações: Expandir + Reimpressão */}
          <div className="mt-2 sm:mt-3 pt-2 sm:pt-3 border-t border-slate-700 flex items-center gap-1 sm:gap-2 flex-wrap">
            <Button
              variant="outline"
              size="sm"
              className="font-bold text-xs sm:text-sm"
              onClick={() => setExpandOpen(true)}
            >
              <Expand className="w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2" />
              <span className="hidden sm:inline">Expandir</span>
              <span className="sm:hidden">Ver</span>
            </Button>

            <div className="ml-auto">
              <OrderReprintButtons
                order={order as any}
                variant="outline"
                size="sm"
                showLabels={false}
              />
            </div>
          </div>

          {/* Action Buttons */}
          {order.status === 'novo' && (
            <div className="flex flex-col gap-1.5 sm:gap-2 mt-3 sm:mt-4">
              {/* Partial Preparation Button */}
              <Button
                onClick={() => setPartialDialogOpen(true)}
                variant="outline"
                className="w-full font-bold text-xs sm:text-sm border-orange-500 text-orange-400 hover:bg-orange-500/20"
              >
                <ListChecks className="w-4 h-4 sm:w-5 sm:h-5 mr-1 sm:mr-2" />
                <span className="hidden sm:inline">Iniciar Preparo (Itens)</span>
                <span className="sm:hidden">Preparo Parcial</span>
              </Button>
              
              {/* Full Preparation Button */}
              <Button
                onClick={() => handleAdvanceStatus()}
                disabled={isUpdating || startAllItemsPreparation.isPending}
                className="w-full font-bold text-sm sm:text-lg py-4 sm:py-6 bg-orange-500 hover:bg-orange-600"
              >
                <ChefHat className="w-4 h-4 sm:w-5 sm:h-5 mr-1 sm:mr-2" />
                <span className="hidden sm:inline">{getNextAction()}</span>
                <span className="sm:hidden">Iniciar Tudo</span>
                <ArrowRight className="w-4 h-4 sm:w-5 sm:h-5 ml-1 sm:ml-2" />
              </Button>
            </div>
          )}

          {order.status === 'preparo' && (
            <Button
              onClick={() => handleAdvanceStatus()}
              disabled={isUpdating}
              className="w-full mt-3 sm:mt-4 font-bold text-sm sm:text-lg py-4 sm:py-6 bg-green-500 hover:bg-green-600"
            >
              <CheckCircle2 className="w-4 h-4 sm:w-5 sm:h-5 mr-1 sm:mr-2" />
              <span className="hidden sm:inline">{getNextAction()}</span>
              <span className="sm:hidden">Pronto</span>
              <ArrowRight className="w-4 h-4 sm:w-5 sm:h-5 ml-1 sm:ml-2" />
            </Button>
          )}

          {order.status === 'pronto' && (
            <Button
              onClick={handleDispatchClick}
              disabled={isUpdating}
              className="w-full mt-3 sm:mt-4 font-bold text-sm sm:text-lg py-4 sm:py-6 bg-blue-500 hover:bg-blue-600"
            >
              {isDeliveryOrder ? <Truck className="w-4 h-4 sm:w-5 sm:h-5 mr-1 sm:mr-2" /> : <Package className="w-4 h-4 sm:w-5 sm:h-5 mr-1 sm:mr-2" />}
              <span className="hidden sm:inline">{getNextAction()}</span>
              <span className="sm:hidden">Despachar</span>
              <ArrowRight className="w-4 h-4 sm:w-5 sm:h-5 ml-1 sm:ml-2" />
            </Button>
          )}
        </CardContent>
      </Card>

      {/* Expand Dialog */}
      <OrderExpandDialog
        open={expandOpen}
        onOpenChange={setExpandOpen}
        order={order as any as Order}
      />

      {/* Partial Preparation Dialog */}
      <PartialPreparationDialog
        open={partialDialogOpen}
        onOpenChange={setPartialDialogOpen}
        items={order.items}
        orderId={order.id}
        orderNumber={(order as any).order_number?.toString()}
        onConfirm={handlePartialConfirm}
        isLoading={updateMultipleItemsStatus.isPending}
      />

      {/* Dispatch Dialog - for delivery orders */}
      <DispatchDialog
        open={dispatchDialogOpen}
        onOpenChange={setDispatchDialogOpen}
        orderNumber={(order as any).order_number}
        onConfirm={handleDispatchConfirm}
        isLoading={isUpdating}
      />
    </>
  );
}
