/**
 * Zoopi Print Agent (PowerShell)
 *
 * Gera um pacote super simples para Windows:
 * - INICIAR.bat
 * - agent.ps1
 *
 * Não precisa de Node.js.
 * O agente expõe uma API local em http://127.0.0.1:3848
 */

function downloadTextFile(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/**
 * Mantemos assinatura compatível com as funções antigas.
 * (Os params do backend não são mais necessários neste agente.)
 */
export function downloadPrintAgentPowerShell(_companyId: string, _backendUrl: string, _backendKey: string) {
  const iniciarBat = [
    '@echo off',
    'chcp 65001 >nul',
    'title Zoopi Print Agent (PowerShell)',
    'cd /d "%~dp0"',
    '',
    ':: Requer Admin para criar bindings HTTPS (netsh urlacl/sslcert)',
    'net session >nul 2>&1',
    'if %errorLevel% neq 0 (',
    '  echo.',
    '  echo [!] Precisa abrir como ADMINISTRADOR. Pedindo permissao...',
    '  powershell -NoProfile -ExecutionPolicy Bypass -Command "Start-Process -FilePath \"%~f0\" -Verb RunAs"',
    '  exit /b',
    ')',
    '',
    'echo ========================================',
    'echo   ZOOPI PRINT AGENT (SEM NODE.JS)',
    'echo ========================================',
    'echo.',
    'echo Rodando agente (tentando portas 3848-3852)...',
    'echo (Se o Windows perguntar, permita no Firewall)',
    'echo.',
    '',
    'powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0agent.ps1"',
    '',
    'echo.',
    'echo Agente finalizado.',
    'pause',
    '',
  ].join('\r\n');

  // IMPORTANT: sem usar crases/backticks do PowerShell aqui dentro (para não quebrar o template string TS).
  // Este agente sobe HTTPS em 127.0.0.1:3848 para evitar bloqueio de Mixed Content
  // quando o sistema roda em HTTPS.
  const agentPs1 = [
    '# Zoopi Print Agent (PowerShell)',
    '# - Sem Node.js',
    '# - HTTPS em 127.0.0.1:3848 (compatível com sites HTTPS)',
    '# - Endpoints: GET /health, POST /test-connection, POST /print, POST /print-ticket',
    '',
    '$ErrorActionPreference = "Stop"',
    '$NL = [Environment]::NewLine',
    '$portsToTry = @(3848,3849,3850,3851,3852)',
    '$listenIP = "127.0.0.1"',
    '$agentPort = $null',
    '',
'# Mata qualquer processo usando a porta',
    'function Kill-PortProcess([int]$port) {',
    '  $conn = netstat -ano | Select-String ":$port " | Select-String "LISTENING"',
    '  if ($conn) {',
    '    foreach ($line in $conn) {',
    '      $parts = $line.Line.Trim() -split "\\s+"',
    '      $procId = $parts[-1]',
    '      if ($procId -match "^\\d+$" -and [int]$procId -gt 0) {',
    '        Write-Host "Matando processo $procId que usava porta $port..." -ForegroundColor Yellow',
    '        try { Stop-Process -Id ([int]$procId) -Force -ErrorAction SilentlyContinue } catch { }',
    '        Start-Sleep -Milliseconds 500',
    '      }',
    '    }',
    '  }',
    '}',
    '',
    'function Ensure-HttpsBinding([int]$Port) {',
    '  # Cria uma CA local (confiável) e um certificado de servidor válido para localhost/127.0.0.1.',
    '  # Objetivo: o fetch() do navegador NÃO pode falhar por certificado inválido.',
    '',
    '  $caName = "Zoopi Local CA"',
    '  $serverCn = "localhost"',
    '',
    '  $ca = Get-ChildItem Cert:\\LocalMachine\\My | Where-Object { $_.Subject -eq "CN=$caName" } | Select-Object -First 1',
    '  if (-not $ca) {',
    '    Write-Host "Criando CA local e confiando no Windows..." -ForegroundColor Yellow',
    '    $ca = New-SelfSignedCertificate -Type Custom -Subject "CN=$caName" -KeyAlgorithm RSA -KeyLength 2048 -HashAlgorithm sha256 -KeyExportPolicy Exportable -KeyUsageProperty Sign -KeyUsage CertSign,CRLSign,DigitalSignature -NotAfter (Get-Date).AddYears(10) -TextExtension @("2.5.29.19={text}ca=true&pathlength=0") -CertStoreLocation "Cert:\\LocalMachine\\My"',
    '    $rootStore = New-Object System.Security.Cryptography.X509Certificates.X509Store("Root","LocalMachine")',
    '    $rootStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadWrite)',
    '    $rootStore.Add($ca)',
    '    $rootStore.Close()',
    '  }',
    '',
    '  # Mantém um único cert de servidor com CN=localhost (SAN: localhost + 127.0.0.1).',
    '  $server = Get-ChildItem Cert:\\LocalMachine\\My | Where-Object { $_.Subject -eq "CN=$serverCn" } | Select-Object -First 1',
    '  if ($server -and $server.Issuer -ne $ca.Subject) {',
    '    Write-Host "Cert de servidor antigo (issuer diferente). Recriando..." -ForegroundColor Yellow',
    '    try { Remove-Item -Path ("Cert:\\LocalMachine\\My\\" + $server.Thumbprint) -Force -ErrorAction SilentlyContinue } catch { }',
    '    $server = $null',
    '  }',
    '  if (-not $server) {',
    '    Write-Host "Criando certificado HTTPS (CN=localhost; SAN=localhost+127.0.0.1) assinado pela CA..." -ForegroundColor Yellow',
    '    $server = New-SelfSignedCertificate -Type Custom -Subject "CN=$serverCn" -KeyAlgorithm RSA -KeyLength 2048 -HashAlgorithm sha256 -KeyExportPolicy Exportable -KeyUsage DigitalSignature,KeyEncipherment -NotAfter (Get-Date).AddYears(5) -Signer $ca -TextExtension @(',
    '      "2.5.29.37={text}1.3.6.1.5.5.7.3.1",',
    '      "2.5.29.17={text}dns=localhost&ipaddress=127.0.0.1"',
    '    ) -CertStoreLocation "Cert:\\LocalMachine\\My" -FriendlyName "Zoopi Print Agent"',
    '  }',
    '',
    '  # URL ACL (para HttpListener) - registra HTTPS (localhost e 127.0.0.1) e HTTP (somente 127.0.0.1)',
    '  $urlLocalhostHttps = "https://localhost:" + $Port + "/"',
    '  $urlLoopbackHttps  = "https://127.0.0.1:" + $Port + "/"',
    '  $urlLoopbackHttp   = "http://127.0.0.1:" + $Port + "/"',
    '',
    '  # Limpa reservas antigas (URLACL) que causam: "conflito com um registro existente"',
    '  try { & netsh http delete urlacl url="$urlLocalhostHttps" | Out-Null } catch { }',
    '  try { & netsh http delete urlacl url="$urlLoopbackHttps"  | Out-Null } catch { }',
    '  try { & netsh http delete urlacl url="$urlLoopbackHttp"   | Out-Null } catch { }',
    '',
    '  try { & netsh http add urlacl url="$urlLocalhostHttps" user=Everyone | Out-Null } catch { }',
    '  try { & netsh http add urlacl url="$urlLoopbackHttps"  user=Everyone | Out-Null } catch { }',
    '  try { & netsh http add urlacl url="$urlLoopbackHttp"   user=Everyone | Out-Null } catch { }',
    '',
    '  # SSL cert binding (limpa em todos os formatos comuns)',
    '  $appid = "{00112233-4455-6677-8899-AABBCCDDEEFF}"',
    '  foreach ($ip in @("0.0.0.0","127.0.0.1","[::]")) {',
    '    $ipport = $ip + ":" + $Port',
    '    try { & netsh http delete sslcert ipport=$ipport | Out-Null } catch { }',
    '  }',
    '  $ipportAny = "0.0.0.0:" + $Port',
    '  try { & netsh http add sslcert ipport=$ipportAny certhash=$($server.Thumbprint) appid=$appid | Out-Null } catch { }',
    '}',
    '',
    'function Get-Origin($ctx) {',
    '  $origin = $ctx.Request.Headers["Origin"]',
    '  if ([string]::IsNullOrWhiteSpace($origin)) { return "*" }',
    '  return $origin',
    '}',
    '',
    'function Add-CorsHeaders($ctx) {',
    '  $origin = Get-Origin $ctx',
    '  $ctx.Response.Headers.Remove("Access-Control-Allow-Origin") | Out-Null',
    '  $ctx.Response.Headers.Add("Access-Control-Allow-Origin", $origin)',
    '  $ctx.Response.Headers.Add("Vary", "Origin")',
    '  $ctx.Response.Headers.Add("Access-Control-Allow-Methods", "GET,POST,OPTIONS")',
    '  $ctx.Response.Headers.Add("Access-Control-Allow-Headers", "content-type,authorization,access-control-request-private-network")',
    '  $ctx.Response.Headers.Add("Access-Control-Allow-Private-Network", "true")',
    '}',
    '',
    'function Write-JsonResponse($ctx, [int]$statusCode, $obj) {',
    '  $json = $obj | ConvertTo-Json -Depth 10 -Compress',
    '  $bytes = [System.Text.Encoding]::UTF8.GetBytes($json)',
    '  $ctx.Response.StatusCode = $statusCode',
    '  $ctx.Response.ContentType = "application/json; charset=utf-8"',
    '  Add-CorsHeaders $ctx',
    '  $ctx.Response.OutputStream.Write($bytes, 0, $bytes.Length)',
    '  $ctx.Response.OutputStream.Close()',
    '}',
    '',
    'function Write-TextResponse($ctx, [int]$statusCode, [string]$text) {',
    '  $bytes = [System.Text.Encoding]::UTF8.GetBytes($text)',
    '  $ctx.Response.StatusCode = $statusCode',
    '  $ctx.Response.ContentType = "text/plain; charset=utf-8"',
    '  Add-CorsHeaders $ctx',
    '  $ctx.Response.OutputStream.Write($bytes, 0, $bytes.Length)',
    '  $ctx.Response.OutputStream.Close()',
    '}',
    '',
    'function Read-Body($req) {',
    '  if (-not $req.HasEntityBody) { return "" }',
    '  $sr = New-Object System.IO.StreamReader($req.InputStream, $req.ContentEncoding)',
    '  $body = $sr.ReadToEnd()',
    '  $sr.Close()',
    '  return $body',
    '}',
    '',
    'function Test-Tcp([string]$h, [int]$p, [int]$timeoutMs = 2000) {',
    '  try {',
    '    $client = New-Object System.Net.Sockets.TcpClient',
    '    $iar = $client.BeginConnect($h, $p, $null, $null)',
    '    if (-not $iar.AsyncWaitHandle.WaitOne($timeoutMs, $false)) {',
    '      $client.Close()',
    '      return @{ success = $false; error = "Timeout" }',
    '    }',
    '    $client.EndConnect($iar)',
    '    $client.Close()',
    '    return @{ success = $true }',
    '  } catch {',
    '    return @{ success = $false; error = $_.Exception.Message }',
    '  }',
    '}',
    '',
    'function Send-ToPrinter([string]$h, [int]$p, [byte[]]$bytes, [int]$timeoutMs = 8000) {',
    '  $client = New-Object System.Net.Sockets.TcpClient',
    '  $client.SendTimeout = $timeoutMs',
    '  $client.ReceiveTimeout = $timeoutMs',
    '  $client.Connect($h, $p)',
    '  $stream = $client.GetStream()',
    '  $stream.Write($bytes, 0, $bytes.Length)',
    '  $stream.Flush()',
    '  $stream.Close()',
    '  $client.Close()',
    '}',
    '',
    'function Build-PrintBytes([string]$content, [bool]$cut, [bool]$beep) {',
    '  $ESC = 0x1B',
    '  $GS  = 0x1D',
    '  $init = [byte[]]@($ESC, 0x40)',
    '  $beepCmd = [byte[]]@($ESC, 0x42, 0x05, 0x02)',
    '  $cutCmd = [byte[]]@($GS, 0x56, 0x00)',
    '  $enc = [System.Text.Encoding]::GetEncoding(860)',
    '  $text = $enc.GetBytes($content)',
    '  $tail = [System.Text.Encoding]::ASCII.GetBytes("\\r\\n\\r\\n\\r\\n\\r\\n")',
    '  $all = New-Object System.Collections.Generic.List[byte]',
    '  $all.AddRange($init)',
    '  if ($beep) { $all.AddRange($beepCmd) }',
    '  $all.AddRange($text)',
    '  if ($cut) { $all.AddRange($tail); $all.AddRange($cutCmd) }',
    '  return $all.ToArray()',
    '}',
    '',
    'function Format-Ticket($ticket) {',
    '  $lines = New-Object System.Collections.Generic.List[string]',
    '  $sector = if ($ticket.sectorName) { $ticket.sectorName } else { "COZINHA" }',
    '',
    '  # Cabeçalho com destaque',
    '  $lines.Add("")',
    '  $lines.Add(("=" * 42))',
    '  $lines.Add("      *** $sector ***")',
    '  $lines.Add(("=" * 42))',
    '',
    '  # Número do pedido em GRANDE DESTAQUE',
    '  $lines.Add("")',
    '  $orderNum = if ($ticket.orderNumber) { $ticket.orderNumber } else { "---" }',
    '  $lines.Add(("*" * 42))',
    '  $lines.Add("*         PEDIDO #$orderNum         *")',
    '  $lines.Add(("*" * 42))',
    '  $lines.Add("")',
    '',
    '  # Módulo/Origem do pedido (DELIVERY, MESA, COMANDA, QR CODE, etc)',
    '  $orderType = ""',
    '  if ($ticket.orderType) { $orderType = $ticket.orderType.ToUpper() }',
    '  elseif ($ticket.receiptType) {',
    '    switch ($ticket.receiptType.ToLower()) {',
    '      "delivery" { $orderType = "DELIVERY" }',
    '      "entrega" { $orderType = "DELIVERY" }',
    '      "table" { $orderType = "MESA" }',
    '      "mesa" { $orderType = "MESA" }',
    '      "comanda" { $orderType = "COMANDA" }',
    '      "counter" { $orderType = "BALCAO" }',
    '      "balcao" { $orderType = "BALCAO" }',
    '      "qrcode" { $orderType = "QR CODE" }',
    '      "qr_code" { $orderType = "QR CODE" }',
    '      "local" { $orderType = "COMER AQUI" }',
    '      "dine_in" { $orderType = "COMER AQUI" }',
    '      "takeaway" { $orderType = "LEVAR" }',
    '      "levar" { $orderType = "LEVAR" }',
    '      "retirada" { $orderType = "RETIRADA" }',
    '      "pickup" { $orderType = "RETIRADA" }',
    '      default { $orderType = $ticket.receiptType.ToUpper() }',
    '    }',
    '  }',
    '',
    '  if ($orderType) {',
    '    $lines.Add(">>> $orderType <<<")',
    '    $lines.Add("")',
    '  }',
    '',
    '  # Origem (ONLINE, QR CODE)',
    '  $source = ""',
    '  if ($ticket.source) { $source = $ticket.source.ToUpper() }',
    '  if ($source -eq "ONLINE" -or $source -eq "QRCODE" -or $source -eq "QR_CODE") {',
    '    $lines.Add("*** PEDIDO ONLINE ***")',
    '    $lines.Add("")',
    '  }',
    '',
    '  # Modo de consumo (COMER AQUI / LEVAR)',
    '  $eatIn = $ticket.eatIn',
    '  if ($eatIn -eq $true) { $lines.Add("[ COMER AQUI ]"); $lines.Add("") }',
    '  elseif ($eatIn -eq $false) { $lines.Add("[ LEVAR ]"); $lines.Add("") }',
    '',
    '  # Mesa',
    '  if ($ticket.tableNumber) {',
    '    $lines.Add("+---------------------------------+")',
    '    $lines.Add("|     *** MESA $($ticket.tableNumber) ***     |")',
    '    $lines.Add("+---------------------------------+")',
    '    $lines.Add("")',
    '  } elseif ($ticket.tableName) {',
    '    $lines.Add("MESA: $($ticket.tableName)")',
    '    $lines.Add("")',
    '  }',
    '',
    '  # Comanda',
    '  if ($ticket.commandNumber) {',
    '    $lines.Add(">>> COMANDA #$($ticket.commandNumber) <<<")',
    '    if ($ticket.commandName) { $lines.Add("Nome: $($ticket.commandName)") }',
    '    $lines.Add("")',
    '  }',
    '',
    '  # Data/Hora',
    '  $lines.Add("Data: $(Get-Date -Format \\"dd/MM/yyyy HH:mm\\")")',
    '',
    '  # Cliente',
    '  if ($ticket.customerName) { $lines.Add("Cliente: $($ticket.customerName)") }',
    '  if ($ticket.customerPhone) { $lines.Add("Fone: $($ticket.customerPhone)") }',
    '  if ($ticket.customerAddress) { $lines.Add("Endereco: $($ticket.customerAddress)") }',
    '  if ($ticket.addressNotes) { $lines.Add(">>> $($ticket.addressNotes.ToUpper()) <<<") }',
    '',
    '  $lines.Add(("-" * 42))',
    '',
    '  # Itens',
    '  $lines.Add("ITENS:")',
    '  $lines.Add("")',
    '  if ($ticket.items) {',
    '    foreach ($it in $ticket.items) {',
    '      $status = ""',
    '      if ($it.editStatus -eq "new") { $status = "*** NOVO *** " }',
    '      elseif ($it.editStatus -eq "modified") { $status = ">>> ALTERADO <<< " }',
    '      elseif ($it.editStatus -eq "removed") { $status = "XXX REMOVIDO XXX " }',
    '',
    '      $lines.Add("$status$($it.quantity)x $($it.name)")',
    '      if ($it.options) { foreach ($op in $it.options) { $lines.Add("   > $op") } }',
    '      if ($it.notes) { $lines.Add("   OBS: $($it.notes)") }',
    '      $lines.Add("")',
    '    }',
    '  }',
    '',
    '  # Observações gerais',
    '  if ($ticket.notes) {',
    '    $lines.Add(("-" * 42))',
    '    $lines.Add("*** OBSERVACOES ***")',
    '    $lines.Add($ticket.notes.ToUpper())',
    '    $lines.Add("")',
    '  }',
    '',
    '  # Rodapé',
    '  $lines.Add(("=" * 42))',
    '  $lines.Add("Impresso: $(Get-Date -Format \\"dd/MM/yyyy HH:mm:ss\\")")',
    '  $lines.Add("")',
    '  $lines.Add("www.zoopi.app.br / Tel (16) 98258.6199")',
    '  $lines.Add("")',
    '  $lines.Add("")',
    '',
    '  return ($lines -join $NL)',
    '}',
    '',
    '# Tenta subir em uma porta livre (3848-3852). Se houver conflito de URLACL/HttpListener, tenta a proxima.',
    'foreach ($p in $portsToTry) {',
    '  try {',
    '    Write-Host "Tentando iniciar na porta $p..." -ForegroundColor DarkGray',
    '    Kill-PortProcess $p',
    '    Ensure-HttpsBinding -Port $p',
    '    $listener = New-Object System.Net.HttpListener',
    '    $prefixHttpsLoopback = "https://" + $listenIP + ":" + $p + "/"',
    '    $prefixHttpsLocalhost = "https://localhost:" + $p + "/"',
    '    $prefixHttpLoopback = "http://" + $listenIP + ":" + $p + "/"',
    '    $listener.Prefixes.Add($prefixHttpsLoopback)',
    '    $listener.Prefixes.Add($prefixHttpsLocalhost)',
    '    $listener.Prefixes.Add($prefixHttpLoopback)',
    '    $listener.Start()',
    '    $agentPort = $p',
    '    Write-Host "Zoopi Print Agent rodando em $prefixHttpsLoopback (e $prefixHttpsLocalhost)" -ForegroundColor Green',
    '    Write-Host "Teste (recomendado): https://127.0.0.1:$agentPort/health" -ForegroundColor DarkGray',
    '    Write-Host "HTTP tambem funciona via: http://127.0.0.1:$agentPort/health" -ForegroundColor DarkGray',
    '    break',
    '  } catch {',
    '    Write-Host "Falhou na porta ${p}: $($_.Exception.Message)" -ForegroundColor Yellow',
    '    try { if ($listener) { $listener.Close() } } catch { }',
    '    $listener = $null',
    '  }',
    '}',
    '',
    'if (-not $agentPort) {',
    '  Write-Host "Nao foi possivel iniciar o agente em nenhuma porta (3848-3852)." -ForegroundColor Red',
    '  Write-Host "Dica: rode este comando como Administrador e tente novamente:" -ForegroundColor DarkGray',
    '  Write-Host "  netsh http show urlacl | findstr 3848" -ForegroundColor DarkGray',
    '  throw "Falha ao iniciar HttpListener"',
    '}',
    '',
    'while ($true) {',
    '  $ctx = $listener.GetContext()',
    '  try {',
    '    $req = $ctx.Request',
    '    $path = $req.Url.AbsolutePath',
    '    $method = $req.HttpMethod',
    '',
    '    if ($method -eq "OPTIONS") {',
    '      $ctx.Response.StatusCode = 204',
    '      Add-CorsHeaders $ctx',
    '      $ctx.Response.OutputStream.Close()',
    '      continue',
    '    }',
    '',
    '    if ($method -eq "GET" -and $path -eq "/health") {',
    '      Write-TextResponse $ctx 200 "ok"',
    '      continue',
    '    }',
    '',
    '    if ($method -eq "POST" -and $path -eq "/test-connection") {',
    '      $body = Read-Body $req',
    '      $data = $body | ConvertFrom-Json',
    '      $h = [string]$data.host',
    '      $p = [int]$data.port',
    '      $result = Test-Tcp $h $p 2500',
    '      Write-JsonResponse $ctx 200 $result',
    '      continue',
    '    }',
    '',
    '    if ($method -eq "POST" -and $path -eq "/print") {',
    '      $body = Read-Body $req',
    '      $data = $body | ConvertFrom-Json',
    '      $h = [string]$data.host',
    '      $p = if ($data.port) { [int]$data.port } else { 9100 }',
    '      $content = [string]$data.content',
    '      $copies = if ($data.copies) { [int]$data.copies } else { 1 }',
    '      $cut = if ($null -ne $data.cut) { [bool]$data.cut } else { $true }',
    '      $beep = if ($null -ne $data.beep) { [bool]$data.beep } else { $false }',
    '      for ($i = 0; $i -lt $copies; $i++) {',
    '        $bytes = Build-PrintBytes $content $cut $beep',
    '        Send-ToPrinter $h $p $bytes',
    '      }',
    '      Write-JsonResponse $ctx 200 @{ success = $true; printedAt = (Get-Date).ToString("o") }',
    '      continue',
    '    }',
    '',
    '    if ($method -eq "POST" -and $path -eq "/print-ticket") {',
    '      $body = Read-Body $req',
    '      $data = $body | ConvertFrom-Json',
    '      $h = [string]$data.host',
    '      $p = if ($data.port) { [int]$data.port } else { 9100 }',
    '      $ticket = $data.ticket',
    '      $copies = if ($data.copies) { [int]$data.copies } else { 1 }',
    '      $beep = if ($null -ne $data.beep) { [bool]$data.beep } else { $true }',
    '      $text = Format-Ticket $ticket',
    '      for ($i = 0; $i -lt $copies; $i++) {',
    '        $bytes = Build-PrintBytes $text $true $beep',
    '        Send-ToPrinter $h $p $bytes',
    '      }',
    '      Write-JsonResponse $ctx 200 @{ success = $true; printedAt = (Get-Date).ToString("o") }',
    '      continue',
    '    }',
    '',
    '    Write-JsonResponse $ctx 404 @{ success = $false; error = "Not found" }',
    '  } catch {',
    '    try { Write-JsonResponse $ctx 500 @{ success = $false; error = $_.Exception.Message } } catch { }',
    '  }',
    '}',
    '',
  ].join('\r\n');

  downloadTextFile('INICIAR.bat', iniciarBat);
  downloadTextFile('agent.ps1', agentPs1);
}
